format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$line_break\ 
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$cmd_duration\
$character"""

command_timeout = 1000

# Disable add newline after prompt
add_newline = false

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold green)'

# Set command execution time style
[cmd_duration]
format = ' [$duration ]($style)'

# To add brackets around certain modules
[directory]
truncation_length = 2
fish_style_pwd_dir_length = 1 # These two truncation show [~/D/C/current-dir]
format = '[$path]($style) '

[battery]
[[battery.display]]
threshold = 0

[git_commit]
format = '[\($hash\)]($style)'
only_detached = true # change this to false to always see commit hash

[git_branch]
symbol = ' '
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style)) '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[c]
symbol = "++ "
format = "via [g$symbol$version]($style) "
style = "bold #a8c558"

[guix_shell]
format = '\[[$symbol]($style)\] '

[hostname]
ssh_only = false
ssh_symbol = '󱘖 '
format = '[$ssh_symbol](bold #0087d7) on [$hostname](bold #29a1e8) '
trim_at = '.local'
disabled = false

[username]
format = '[$user](#0087d7)'
disabled = false
show_always = true

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'
