#!/usr/bin/env sh

# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
# yabai --uninstall-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

### RULES ###
# yabai -m rule									\
# 	--add app="mpv" manage=off					\
# 	--add app="System Settings" manage=off		\
# 	--add app="App Store" manage=off			\
# 	--add app="FaceTime" manage=off				\
# 	--add app="Find My" manage=off				\
# 	--add app="Dictionary" manage=off			\
# 	--add app="Alfred Preferences" manage=off
yabai -m rule --add app="mpv" manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="App Store" manage=off
yabai -m rule --add app="FaceTime" manage=off
yabai -m rule --add app="Find My" manage=off
yabai -m rule --add app="Dictionary" manage=off
yabai -m rule --add app="Books" title!="(Home|Books|Book Store|Audiobook Store|All|Want to Read|Finished|Audiobooks|PDFs|My Samples)" manage=off grid=8:8:2:0:4:8
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off

# Scratchpads
yabai -m rule --add app="^Spotify$" scratchpad=sp_music
yabai -m rule --add app="^Mail$" scratchpad=sp_mail
yabai -m rule --add app="^Messages$" scratchpad=sp_messages
yabai -m rule --add app="^Calendar$" scratchpad=sp_calendar
yabai -m rule --add app="^Books$" scratchpad=sp_books
# yabai -m rule --add app="^Bitwarden$" scratchpad=sp_bitwarden

# To Make Find My A Good Size
for i in {1..10}; do
  window_id=$(yabai -m query --windows | jq -r '.[] | select(.app == "Find My") | .id')
  if [ -n "$window_id" ]; then
    break
  fi
  sleep 0.5
done
yabai -m window $window_id --resize abs:1572:1032
yabai -m window $window_id --move abs:140:90


### GENERAL CONFIG ###
yabai -m config                                 \
	external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          on             \
    focus_follows_mouse          autofocus      \
    display_arrangement_order    default        \
    window_origin_display        cursor         \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                off            \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
	window_border				 off			\
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    window_balance               on             \
    insert_feedback_color        0xffD08770     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  10             \
    bottom_padding               10             \
    left_padding                 10             \
    right_padding                10             \
    window_gap                   10             \
    layout                       bsp            \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"

borders &
sh ~/.config/yabai/scripts/focus_follows_mouse.sh &
sh ~/.config/yabai/scripts/cleanup_spaces.sh &

# Downloads and runs the latest yabai autoupdate script on startup or when run.
# YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &
